# Generated by Django 3.0.3 on 2020-03-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='managers',
            field=models.ManyToManyField(limit_choices_to={'designation': 'MGR'}, to='Employee.Employee'),
        ),
    ]
