# Generated by Django 3.0.3 on 2020-03-07 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0003_employee_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursement_type', models.CharField(choices=[('TravellingA', 'TravellingA'), ('SpecialA', 'SpecialA'), ('MedicalA', 'MedicalA'), ('BusinessA', 'BusinessA')], default='TravellingA', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('file_1', models.FileField(upload_to='reimbursements/%Y/%m/%d')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='reimbursements/%Y/%m/%d')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='reimbursements/%Y/%m/%d')),
                ('date_of_reimbursement', models.DateField()),
                ('date_of_application', models.DateField(auto_now=True)),
                ('approval', models.CharField(choices=[('accept', 'accept'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('included_in_salary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
