# Generated by Django 3.0.3 on 2020-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='reimbursements/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursement_type',
            field=models.CharField(choices=[('TravellingA', 'Travelling Allowance'), ('SpecialA', 'Special Allowance'), ('MedicalA', 'Medical Allowance'), ('BusinessA', 'Business Allowance')], default='TravellingA', max_length=50),
        ),
    ]
