# Generated by Django 3.0.3 on 2020-03-07 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0005_auto_20200307_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('FullDay', 'Full Day'), ('SpecialA', 'Special Allowance')], default='FullDay', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('date_of_leave', models.DateField()),
                ('time_of_leave', models.TimeField(blank=True, null=True)),
                ('approval', models.CharField(choices=[('accept', 'accept'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
