# Generated by Django 3.0.3 on 2020-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='included_in_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('FullDay', 'Full Day'), ('HalfDay', 'Half Day')], default='FullDay', max_length=50),
        ),
    ]
