# Generated by Django 3.0.3 on 2020-03-07 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_employeeworkinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinghour',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeworkinghour',
            name='today_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 18, 35, 51, 19335, tzinfo=utc)),
        ),
    ]
