# Generated by Django 3.0.3 on 2020-03-08 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_auto_20200308_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='today_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 2, 6, 56, 772817, tzinfo=utc)),
        ),
    ]
