# Generated by Django 3.0.3 on 2020-03-08 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_auto_20200308_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='today_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 3, 16, 32, 926173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default='3000', max_digits=10),
        ),
    ]
